language: php

branches:
  only:
    - master

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - hhvm

before_script:
  # Composer
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

#  - ./test/reset_tests.sh

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
